application.data-dir: /home/andikaharis/Documents
server.port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:3306/course_api
    username: root
    password: root123
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
  messages.basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
